# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYyMDRiMTg3YjhmMDU1YmFjODJjNzgiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiIiLCJpYXQiOjE2OTM1ODI1OTcsImV4cCI6MTY5MzU4MzE5N30.4nXoBIK1URXW89I4kp7FgxOALPVMTWm8b9CnCHB_IYc

###
# Create a new post
POST http://localhost:4000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYyMDRiMTg3YjhmMDU1YmFjODJjNzgiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiIiLCJpYXQiOjE2OTM1ODI1OTcsImV4cCI6MTY5MzU4MzE5N30.4nXoBIK1URXW89I4kp7FgxOALPVMTWm8b9CnCHB_IYc
Content-Type: application/json

{
  "title": "Проверка!!",
  "type": "text"
}
###