@token={{login.response.body.accessToken}}
# @name login
# Login user by email and password

POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "coach@test.local",
  "password": "123456"
}

###

# Create workout
POST http://localhost:3002/api/workout/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Yoga 3",
  "background": "image.jpg",
  "level": "beginner",
  "type": "yoga",
  "timeOfTraining": "30-50",
  "price": 1500,
  "caloriesToSpend": 1500,
  "description": "Yoga for beginners",
  "gender": "indifferent",
  "video": "/img/content/training-video/video-thumbnail",
  "special": false
}

###

# Update workout by ID
PATCH http://localhost:3002/api/workout/list/coach/3 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Yoga for all",
  "timeOfTraining": "50-80"
}

###

# Get workout by ID
GET http://localhost:3002/api/workout/list/coach/3 HTTP/1.1
Authorization: Bearer {{token}}

###

# Get all workouts and filtres
POST http://localhost:3002/api/workout/list HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "limit": 6,
  "page": 1,
  "sortBy": "createdDate",
  "caloriesToSpend": "1000,2000",
  "price": "100,5000",
  "type": "yoga",
  "rating": "0,5",
  "timeOfTraining": "",
  "sortDirection": "asc"
}

###

# Get count workouts
POST http://localhost:3002/api/workout/list/count HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{  
  "limit": 6,
  "page": 1,
  "sortBy": "createdDate",
  "caloriesToSpend": "1000,2000",
  "price": "100,5000",
  "type": "yoga",
  "rating": "0,5",
  "timeOfTraining": "",
  "sortDirection": "asc"
}

###

# Get all coach workouts
GET http://localhost:3002/api/workout/list/coach HTTP/1.1
Authorization: Bearer {{token}}

###

# Delete workout
DELETE  http://localhost:3002/api/workout/list/coach/1 HTTP/1.1
Authorization: Bearer {{token}}

###