version: '3.5'
services:
  fitfriends.workouts.postgres:
    image: postgres:14-alpine
    container_name: fitfriends.workouts.postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - $POSTGRES_PORT:5432
    restart: always
    volumes:
      - fitfriends.workouts.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fitfriends.workouts

  fitfriends.workouts.pgadmin:
    image: dpage/pgadmin4
    container_name: fitfriends.workouts.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PW
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - fitfriends.workouts

volumes:
  fitfriends.workouts.postgres:

networks:
  fitfriends.workouts:
      driver: bridge
