@token={{login.response.body.accessToken}}
# @name login
# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@test1.local",
  "password": "123456"
}

###


# Get user by ID
GET http://localhost:3001/api/user/6535430009ad33414280b094 HTTP/1.1
Authorization: Bearer {{token}}

###

# Get user list
GET http://localhost:3001/api/user/list HTTP/1.1
Authorization: Bearer {{token}}

###

# Get user friends list
GET http://localhost:3001/api/user/list/friends HTTP/1.1
Authorization: Bearer {{token}}

###

# Update user information 
PATCH http://localhost:3001/api/user/update HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Test Name",
  "description": "Колдовство, предательство и необыкновенный мир фэнтези.",
  "caloriesToReset": 3000,
  "trainingReady": true
}

###

# Get user by ID
GET http://localhost:3001/api/user/list/friends/652ffdf03cb7412c4cd5994a HTTP/1.1
Authorization: Bearer {{token}}

###

# Follow user
PATCH http://localhost:3001/api/user/list/friends/follow/652ffdf03cb7412c4cd5994a HTTP/1.1
Authorization: Bearer {{token}}

###
# Unfollow user
PATCH http://localhost:3001/api/user/list/friends/unfollow/6535430009ad33414280b094 HTTP/1.1
Authorization: Bearer {{token}}

###

# Add user to friends
PATCH http://localhost:3001/api/user/friends/add/652ffdf03cb7412c4cd5994a HTTP/1.1
Authorization: Bearer {{token}}

###

# Remove user to friends
PATCH http://localhost:3001/api/user/friends/remove/652ffdf03cb7412c4cd5994a HTTP/1.1
Authorization: Bearer {{token}}

###
