@token={{login.response.body.accessToken}}
# @name login
# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.local",
  "password": "123456"
}

###

# Create request
POST http://localhost:3004/api/request/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "6530088c4c247c402951848f"
}
###

# Update request by ID
PATCH http://localhost:3004/api/request/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "accept"
}

###

# Get request by ID
GET http://localhost:3004/api/request/1 HTTP/1.1
Authorization: Bearer {{token}}

###

# Get inputs requests
GET http://localhost:3004/api/request/list/input HTTP/1.1
Authorization: Bearer {{token}}

###

# Get my requests
GET http://localhost:3004/api/request/list/requester HTTP/1.1
Authorization: Bearer {{token}}

###

# Delete request
DELETE  http://localhost:3004/api/request/3 HTTP/1.1
Authorization: Bearer {{token}}

