@token={{login.response.body.accessToken}}
# @name login
# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.local",
  "password": "123456"
}

###

# Create feedback
POST http://localhost:3002/api/feedback/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "workoutId": 3,
  "rating": 4,
  "text": "Мне понравилось, тренер просто лапушка. Подходил, помогал, объяснял асаны. У нее теплые руки. Мне понравилось, тренер просто лапушка. Подходил, помогал, объяснял асаны. У нее теплые руки"
}

###

# Get feedbacks by workout ID
POST http://localhost:3002/api/feedback/list/3 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "limit": 6,
  "page": 1
}

###

# Get feedback by ID
GET http://localhost:3002/api/feedback/1 HTTP/1.1
Authorization: Bearer {{token}}

###