@token={{login.response.body.accessToken}}
# @name login
# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@test1.local",
  "password": "123456"
}

### 

# Create a new user
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test3@test1.local",
  "name": "Test Doe",
  "password": "123456",
  "avatarId": "C:/img/content/avatars/users/photo-1.png",
  "gender": "male",
  "dateBirth": "2012-02-22",
  "role": "user",
  "description": "Страшный рассказ о драконе. Колдовство, предательство и необыкновенный мир фэнтези.",
  "location": "Пионерская",
  "image": "C:/img/content/avatars/users/photo-1.png",
  "level": "новичок",
  "typeOfTrain": ["йога", "стрейчинг"],
  "timeOfTrain": "50-80",
  "caloriesToReset": 1500,
  "caloriesToSpend": 1500,
  "trainingReady": true
}

###

# Get user by ID
GET http://localhost:3001/api/auth/6535430009ad33414280b094 HTTP/1.1
Authorization: Bearer {{token}}

###

# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer {{token}}

###

# Check user token
POST http://localhost:3001/api/auth/check HTTP/1.1
Authorization: Bearer {{token}}


###
# Change user password
POST http://localhost:3001/api/auth/change-password HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword":"123456",
  "newPassword":"1234567"
}
###

# Get new JWT pair
# @name refresh
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer {{token}}

###
# Check token
# @name check
POST http://localhost:3001/api/auth/check HTTP/1.1
Authorization: Bearer {{token}}

###
